[week1] 프로그래머스 lv.2 알고리즘 풀이
xxziiko/Algorithm-Study pull request #1
Opened 2024-05-07 02:05 UTC by xxziiko

@f-lab-young

2024-05-07 06:13 UTC, f-lab-jake requested changes

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/N개의_최소공배수.js
> +  return a % b ? gcd(b, a % b) : b;
중복을 제거하세요

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/다음_큰_숫자.js
> +		if (count === answer.toString(2).replaceAll("0", "").length) {
중복을 제거하세요

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/올바른_괄호.js
> +		if (stack[stack.length - 1] === "(" && i === ")") stack.pop();
`Array.at`을 쓰세요

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/올바른_괄호.js
> +		if (stack[stack.length - 1] === "(" && i === ")") stack.pop();
그리고 ")))"같은 입력이 들어왔을때 일찌감치 결과를 리턴할 있습니다.

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/이진_변환_반복하기.js
> +	const answer = [0, 0];
그냥 변수 두개를 두세요. 수정가능한 배열은 쓰기 까다롭습니다.

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/이진_변환_반복하기.js
> +		for (const i of number) i === "0" && answer[1]++;
if문을 사용하세요. 삼항연산자나 &&를 활용한 short circuiting은 반환값을 사용할때만 쓰세요.

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/이진_변환_반복하기.js
> +		stringLength = number.length;
이런거 굳이 변수로 안만들어도 됩니다.

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/짝지어_제어하기.js
> +	return stack.length ? 0 : 1;
삼항연산자 안쓸수 있습니다.

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/최솟값_만들기.js
> +  );
lodash import하고 `zip`을 쓰세요

2024-05-07 06:13 UTC, f-lab-jake commented on programmers/피보나치_수.js
> +}
generator 공부해서 적용해보세요

2024-05-07 12:29 UTC, xxziiko commented on programmers/올바른_괄호.js
> +		if (stack[stack.length - 1] === "(" && i === ")") stack.pop();
마지막 말씀이 이해가 잘 안됐습니다..!

2024-05-08 13:30 UTC, xxziiko commented on programmers/다음_큰_숫자.js
> +		if (count === answer.toString(2).replaceAll("0", "").length) {
[f39e422](https://github.com/xxziiko/ts-snippets/pull/1/commits/f39e42277c977b7cd932917eb54bfa3acab25dd6) 수정했습니다!

2024-05-08 13:31 UTC, xxziiko commented on programmers/이진_변환_반복하기.js
> +	const answer = [0, 0];
[d525457](https://github.com/xxziiko/ts-snippets/pull/1/commits/d525457dd69b3aee3967ee8b35ed9a12ca1ee754) 수정했습니다!

2024-05-08 13:32 UTC, xxziiko commented on programmers/이진_변환_반복하기.js
> +		for (const i of number) i === "0" && answer[1]++;
[d525457](https://github.com/xxziiko/ts-snippets/pull/1/commits/d525457dd69b3aee3967ee8b35ed9a12ca1ee754) 수정했습니다!

2024-05-08 13:33 UTC, xxziiko commented on programmers/이진_변환_반복하기.js
> +		stringLength = number.length;
[c835cb5](https://github.com/xxziiko/ts-snippets/pull/1/commits/c835cb5d9b6a2116df44ab31d7acfae153ca01ef) 수정했습니다!

2024-05-08 13:33 UTC, xxziiko commented on programmers/짝지어_제어하기.js
> +	return stack.length ? 0 : 1;
[607c734](https://github.com/xxziiko/ts-snippets/pull/1/commits/607c734893437f946edf16068296e3f4dd0dbef1) 수정했습니다!

2024-05-08 13:33 UTC, xxziiko commented on programmers/최솟값_만들기.js
> +  );
[bde50b4](https://github.com/xxziiko/ts-snippets/pull/1/commits/bde50b46bc33aa075b4fc151229d27f98ae3da9a) 수정했습니다!

2024-05-08 13:33 UTC, xxziiko commented on programmers/피보나치_수.js
> +}
[92f8929](https://github.com/xxziiko/ts-snippets/pull/1/commits/92f8929b0a63c37a001188ff99ba449c5d6f2879) 수정했습니다!

2024-05-08 13:34 UTC, xxziiko commented on programmers/N개의_최소공배수.js
> +  return a % b ? gcd(b, a % b) : b;
[3696ae9](https://github.com/xxziiko/ts-snippets/pull/1/commits/3696ae9df2d9e60001131b5718e68f7b23c9221e) 수정했습니다!

2024-05-08 13:36 UTC, xxziiko commented
@f-lab-jake
피드백 반영하여 수정완료했습니다!

2024-05-08 13:39 UTC, xxziiko commented on programmers/올바른_괄호.js
> +		if (stack[stack.length - 1] === "(" && i === ")") stack.pop();
[f06ab98](https://github.com/xxziiko/ts-snippets/pull/1/commits/f06ab981d63b879e3d113f53035ea92dd05a314b) 수정 했습니다!

2024-05-08 13:51 UTC, xxziiko commented
@f-lab-jake 
피드백 반영하여 수정완료했습니다!

2024-05-09 01:57 UTC, f-lab-jake requested changes

2024-05-09 01:57 UTC, f-lab-jake commented on programmers/올바른_괄호.js
> +	if (s[0] === ")") return false;
근시안적인 대책입니다. 이걸로 해결안되는 패턴을 떠올려보세요.

2024-05-09 06:03 UTC, xxziiko commented on programmers/이진_변환_반복하기.js
> +		stringLength = number.length;
[c835cb5](https://github.com/xxziiko/ts-snippets/pull/1/commits/c835cb5d9b6a2116df44ab31d7acfae153ca01ef) 수정 했습니다!

2024-05-09 06:04 UTC, xxziiko commented on programmers/올바른_괄호.js
> +	if (s[0] === ")") return false;
@f-lab-jake  [848ee6a](https://github.com/xxziiko/ts-snippets/pull/1/commits/848ee6a55df7f9daf0e9cb784c4319d4b7eb838b) 다시 수정했습니다!

2024-05-10 03:06 UTC, f-lab-jake requested changes

2024-05-10 03:06 UTC, f-lab-jake commented on programmers/올바른_괄호.js
> +	if (s[0] === ")" || s.at(-1) === "(") return false;
예시를 충분히 생각하지않고 손가락이 먼저 나갔습니다.
()) 와 같은 예시를 생각해보세요

2024-05-10 06:46 UTC, xxziiko commented on programmers/올바른_괄호.js
> +	if (s[0] === ")" || s.at(-1) === "(") return false;
@f-lab-jake  흠..! 혹시 이걸 의도하신게 맞을까요 ? [4c0caba](https://github.com/xxziiko/ts-snippets/pull/1/commits/4c0caba3dc710d388652ebefbd9575464b98d28a)

2024-05-12 06:05 UTC, f-lab-jake requested changes

2024-05-12 06:05 UTC, f-lab-jake commented on week1/올바른_괄호.js
> +	if (s.length % 2 === 1 || s[0] === ")") return false;
반례를 스스로 생각해보세요

2024-05-12 06:05 UTC, f-lab-jake commented on week1/올바른_괄호.js
> +	if (s.length % 2 === 1 || s[0] === ")") return false;
이런식으로 케이스하나하나 추가해서는 프로그램을 완성할수 없습니다.

2024-05-12 06:51 UTC, xxziiko commented on week1/올바른_괄호.js
> +	if (s.length % 2 === 1 || s[0] === ")") return false;
다시 수정했습니다!! ㅜㅜ @f-lab-jake

2024-05-13 03:06 UTC, f-lab-jake requested changes

2024-05-13 03:06 UTC, f-lab-jake commented on week1/올바른_괄호.js
> +	if (s[0] === ")" || s.match(/\(/g)?.length !== s.match(/\)/g)?.length)
지금 문제는, 맞는괄호쌍일때 끝까지 확인하는건 당연하고 괜찮은데, 진작에 틀렸을때도 끝까지 확인하는것입니다.
근데 지금 제시한 방법은 일단 여전히 부족한게(반례 있음) 문제고, 두번째론 어차피 저 동작을하느라 문자열을 다 순회하기때문에, 효율성면에서 개선이 없다는게 문제입니다.
스스로의 코드에 대해 공격적으로 반례를 만들어보세요.

2024-05-13 12:46 UTC, xxziiko commented on week1/올바른_괄호.js
> +	if (s[0] === ")" || s.match(/\(/g)?.length !== s.match(/\)/g)?.length)
@f-lab-jake 앗!!! 다시 수정했습니다!

2024-05-21 16:41 UTC, f-lab-jake requested changes

2024-05-21 16:41 UTC, f-lab-jake commented on week1/올바른_괄호.js
> +			}
순서를 바꿔서 return을 먼저 하세요

2024-05-23 07:38 UTC, xxziiko commented on week1/올바른_괄호.js
> +			}
@f-lab-jake 수정했습니다!!

2024-05-23 11:48 UTC, f-lab-jake approved these changes

2024-05-25 05:59 UTC, merged