[week7] 프로그래머스 문제풀이
xxziiko/Algorithm-Study pull request #10
Opened 2024-06-15 15:11 UTC by xxziiko

@f-lab-jake 7주차 문제풀이입니다
lv.1 문제푸는 시간이 너무 오래걸려서 lv.0 위주로 풀었습니다!

2024-06-16 13:16 UTC, f-lab-jake requested changes

2024-06-16 13:16 UTC, f-lab-jake commented on week7/k의개수.ts
> +		for (const string of [...String(i)]) if (string === String(k)) count++;
이런걸로 줄수르 줄이지마세요. 읽기가 더 어렵습니다.

2024-06-16 13:16 UTC, f-lab-jake commented on week7/k의개수.ts
> +		for (const string of [...String(i)]) if (string === String(k)) count++;
그리고 `String(k)`같은걸 반복하지 마세요.

2024-06-16 13:16 UTC, f-lab-jake commented on week7/더크게합치기.ts
> +	return Math.max(Number(String(a) + b), Number(String(b) + a));
문자열과 숫자를 더하는게 의미가 올바른 동작일까요?

2024-06-16 13:16 UTC, f-lab-jake commented on week7/두수의연산값비교하기.ts
> +	return newNumber >= product ? newNumber : product;
`Math.max` 쓰세요

2024-06-16 13:16 UTC, f-lab-jake commented on week7/등수매기기.ts
> +	return average.map((number) => sortedAverage.indexOf(number) + 1);
비효율을 찾아 개선하세요

2024-06-16 13:16 UTC, f-lab-jake commented on week7/로그인성공.ts
> +		if (inputId === id && inputPw !== pw) return "wrong pw";
조건문으 중복을 제거하세요

2024-06-16 13:16 UTC, f-lab-jake commented on week7/소수만들기.ts
> +	}
재귀 써보세요. 지금은 4개 고르라고하면 for문을 한번더 중첩해야겠죠?

2024-06-16 13:16 UTC, f-lab-jake commented on week7/직사각형넓이구하기.ts
> +	return Math.abs((x[0] - x[1]) * (y[0] - y[1]));
destructuring쓰고 좀더 이해가게 고쳐주세요

2024-06-17 08:29 UTC, f-lab-jake requested changes

2024-06-17 08:29 UTC, f-lab-jake commented on week7/k의개수.ts
> +	const numberToString = String(k);
사실 이런건 `num2` `num$` 정도로 해도 괜찮은데요. 원래 이름주기 애매한 변수들이 있습니다.
근데 `numberToString`은 함수에 쓸법한 작명이고 `numberAsString`이 그나마 낫겠네요.

2024-06-17 08:29 UTC, f-lab-jake commented on week7/더크게합치기.ts
> +	return Math.max(Number(String(a) + String(b)), Number(String(b) + String(a)));
딱 고치라고한것만 고치는거보다 더할수있껬죠?

2024-06-17 08:29 UTC, f-lab-jake commented on week7/로그인성공.ts
> +		}
인덴트를 줄여보세요

2024-06-17 08:29 UTC, f-lab-jake commented on week7/직사각형넓이구하기.ts
> +	return Math.abs((x1 - x2) * (y1 - y2));
왜 이렇게 짰는지는 알겠습니다. 이 코드에 숨겨진 전제와 성질에 대한 설명을 준비해옵시다.

2024-06-17 13:15 UTC, xxziiko commented on week7/k의개수.ts
> +	const numberToString = String(k);
`num$` 이라는 변수명은 어떤 의미로 해석하면 되는걸까요??

2024-06-17 13:41 UTC, xxziiko commented on week7/직사각형넓이구하기.ts
> +	return Math.abs((x1 - x2) * (y1 - y2));
넵!!

2024-06-18 06:32 UTC, xxziiko commented on week7/로그인성공.ts
> +		}
[d644fa1](https://github.com/xxziiko/ts-snippets/pull/10/commits/d644fa1429e64b8cab982025d81dae97422313fa) 수정했습니다!

2024-06-18 06:32 UTC, xxziiko commented on week7/더크게합치기.ts
> +	return Math.max(Number(String(a) + String(b)), Number(String(b) + String(a)));
[0be5b4d](https://github.com/xxziiko/ts-snippets/pull/10/commits/0be5b4d08ff63492d009a92ac9486696965676ee) 다시 수정해봤습니다!

2024-06-18 06:33 UTC, xxziiko commented on week7/소수만들기.ts
> +	}
[7d6991c](https://github.com/xxziiko/ts-snippets/pull/10/commits/7d6991c8956b7f727632a6f2611b3d6ad86cc760) 수정했습니다!

2024-06-18 06:33 UTC, xxziiko commented on week7/등수매기기.ts
> +	return average.map((number) => sortedAverage.indexOf(number) + 1);
[00dd8de](https://github.com/xxziiko/ts-snippets/pull/10/commits/00dd8de4e1b555525dc71631d8d0fd1d4f071ccd) 수정해보았습니다!

2024-06-18 06:34 UTC, xxziiko commented
@f-lab-jake 멘토님 피드백 수정완료했습니다!!

2024-06-18 11:07 UTC, f-lab-jake commented on week7/더크게합치기.ts
> +	return Math.max(Number(String(a) + String(b)), Number(String(b) + String(a)));
중복을 고치는 방향을 잘못잡았습니다. 비효율이 여전히 있습니다. 같은 값을 계싼하게 하지마세요.
단순히 비슷한 코드를 모아서 함수를 만드는건 쉽습니다. 왜냐면 여러가지 방법이 있으니까요. 그중에 정답은 하나입니다.

2024-06-18 11:08 UTC, f-lab-jake requested changes

2024-06-18 11:08 UTC, f-lab-jake commented on week7/소수만들기.ts
> +	getSumCombination(nums, 3);
리턴값을 활용하세요.

2024-06-18 11:08 UTC, f-lab-jake commented on week7/소수만들기.ts
> +const combinations: number[] = [];
전역변수를 수정하는 방식을 쓰지말아보세요.

2024-06-18 11:09 UTC, f-lab-jake commented on week7/k의개수.ts
> +	const numberToString = String(k);
별 의미 없습니다. `num2`랑 같은 맥락입니다. 그냥 충돌을 피하기위해 그런 변수명을 지을수도 있습니다.

2024-06-18 11:09 UTC, f-lab-jake commented on week7/로그인성공.ts
> +		}
원래 continue를 쓰라는게 의도인데 이렇게할수도 있겠네요.

2024-06-18 11:18 UTC, xxziiko commented on week7/k의개수.ts
> +	const numberToString = String(k);
아! 이해했습니다

2024-06-18 14:37 UTC, xxziiko commented on week7/더크게합치기.ts
> +	return Math.max(Number(String(a) + String(b)), Number(String(b) + String(a)));
@f-lab-jake  앗!! 다시작성했습니다
[f1bcd6b](https://github.com/xxziiko/ts-snippets/pull/10/commits/f1bcd6bd9f7e56a8e47edf47ce68a122d6ceb0d5)

2024-06-19 03:26 UTC, f-lab-jake commented on week7/더크게합치기.ts
> +	return Math.max(Number(String(a) + String(b)), Number(String(b) + String(a)));
여전한 중복이 있습니다. 그리고 `ab == ba`를 따로 비교할 필요는 없습니다.

2024-06-21 01:51 UTC, xxziiko commented on week7/소수만들기.ts
> +const combinations: number[] = [];
@f-lab-jake  [9702ad4](https://github.com/xxziiko/ts-snippets/pull/10/commits/9702ad4485e9bb0e2e3c1b74138f092a22fe5bfc) 수정했습니다!

2024-06-21 01:52 UTC, xxziiko commented on week7/더크게합치기.ts
> +	return Math.max(Number(String(a) + String(b)), Number(String(b) + String(a)));
@f-lab-jake  [a3ed77b](https://github.com/xxziiko/ts-snippets/pull/10/commits/a3ed77b5af40d32c7a886ffdc54184a17a4d6cf8) 수정했습니다!

2024-06-21 11:02 UTC, f-lab-jake requested changes

2024-06-21 11:02 UTC, f-lab-jake commented on week7/더크게합치기.ts
> +	const ba = String(a) + String(b);
`String(a)` 등을 두번하지 말란 얘깁니다. 공짜가 아닙니다.

2024-06-21 11:02 UTC, f-lab-jake commented on week7/소수만들기.ts
> +			combinations.push(number);
`push`, `pop`를 하지마세요

2024-06-22 08:06 UTC, xxziiko commented on week7/소수만들기.ts
> +			combinations.push(number);
@f-lab-jake [b6231a2](https://github.com/xxziiko/ts-snippets/pull/10/commits/b6231a24ec79ec34580bcb4ea567f0a437d689e9) 다시수정했습니다!

2024-06-22 08:07 UTC, xxziiko commented on week7/더크게합치기.ts
> +	const ba = String(a) + String(b);
@f-lab-jake [e6cac88](https://github.com/xxziiko/ts-snippets/pull/10/commits/e6cac88c6057ec5b9efca1a9341b8ee4a9b7e0bb) 다시 수정해보았는데, 제가 멘토님 말씀을 잘이해 못하는 것 같습니다..ㅠㅠ

2024-06-22 08:21 UTC, f-lab-jake requested changes

2024-06-22 08:21 UTC, f-lab-jake commented on week7/더크게합치기.ts
> +	const ba = numberAsString(b, a);
이렇게 해도 `String(a)`는 2번 실행되겠죠?

2024-06-22 08:21 UTC, f-lab-jake commented on week7/소수만들기.ts
> +				combinations.concat(number),
`.concat([number])`로 합시다. 안좋은 동작입니다.

2024-06-22 08:43 UTC, xxziiko commented on week7/소수만들기.ts
> +				combinations.concat(number),
네!

2024-06-23 13:17 UTC, xxziiko commented on week7/더크게합치기.ts
> +	const ba = numberAsString(b, a);
아하! [d9f507d](https://github.com/xxziiko/ts-snippets/pull/10/commits/d9f507d9044e9a37ea4e85c245b885dc72bea6d1) 다시수정했습니다!

2024-06-24 02:24 UTC, f-lab-jake approved these changes

2024-06-24 04:35 UTC, merged