[week7-1] 프로그래머스 문제풀이
xxziiko/Algorithm-Study pull request #11
Opened 2024-06-18 08:39 UTC by xxziiko

@f-lab-jake

7주차 두번째 문제풀이입니다!

2024-06-18 11:12 UTC, f-lab-jake requested changes

2024-06-18 11:12 UTC, f-lab-jake commented on week7/1로만들기.ts
> +		.reduce((acc, curr) => acc + curr, 0);
`sum`쓰세요

2024-06-18 11:12 UTC, f-lab-jake commented on week7/치킨쿠폰.ts
> +	return calculateMaxServiceChicken(chicken);
이런 함수는 별 의미가 없습니다. 그냥 `solution`과 같잖아요? 그리고 `calculate...` 식의 함수명은 재고해봐야합니다.

2024-06-18 14:38 UTC, xxziiko commented
@f-lab-jake 수정했습니다!!

2024-06-19 06:39 UTC, f-lab-jake requested changes

2024-06-19 06:39 UTC, f-lab-jake commented on week7/치킨쿠폰.ts
> +	return Math.floor(chicken / 10) + solution(restCoupon);
오 재귀를 활요한게 매우 훌륭합니다.

중복을 찾아서 고쳐보세요. 다듬는거만 남았습니다.

2024-06-21 02:16 UTC, xxziiko commented on week7/치킨쿠폰.ts
> +	return Math.floor(chicken / 10) + solution(restCoupon);
@f-lab-jake  [aa21c49](https://github.com/xxziiko/ts-snippets/pull/11/commits/aa21c493a38b0d52b8cc8bb38793cc8730439667) 수정했습니다!

2024-06-21 11:03 UTC, f-lab-jake approved these changes

2024-06-22 06:59 UTC, merged