[week8-1] 프로그래머스 문제풀이입니다!
xxziiko/Algorithm-Study pull request #13
Opened 2024-06-24 14:52 UTC by xxziiko

8주차 두번째 문제풀이 입니다!
@f-lab-jake

2024-06-25 04:43 UTC, f-lab-jake requested changes

2024-06-25 04:43 UTC, f-lab-jake commented on week8/문자열이몇번등장하는지세기.ts
> +		: solution(myString.substring(1), pat);
중복을 줄이세요

2024-06-25 04:43 UTC, f-lab-jake commented on week8/문자열이몇번등장하는지세기.ts
> +	return myString.substring(0, pat.length) === pat
`startsWith`이 있습니다

2024-06-25 04:43 UTC, f-lab-jake commented on week8/문자열이몇번등장하는지세기.ts
> +		: solution(myString.substring(1), pat);
재귀 굳

2024-06-25 04:43 UTC, f-lab-jake commented on week8/배열에서문자열대소문자변환하기.ts
> +		return index % 2 === 1 ? string.toUpperCase() : string.toLowerCase();
요런거 return 빼주세요

2024-06-25 04:43 UTC, f-lab-jake commented on week8/수열과구간쿼리3.ts
> +		arr[j] = temp;
`[arr[i], arr[j]] = [arr[j], arr[i]]`
같은 방법도 있습니다.

2024-06-25 05:32 UTC, xxziiko commented on week8/수열과구간쿼리3.ts
> +		arr[j] = temp;
[05a22da](https://github.com/xxziiko/ts-snippets/pull/13/commits/05a22daa4bc00cc8b497ddaa7ff642d0bb08ea1e) 수정했습니다!

2024-06-25 05:32 UTC, xxziiko commented on week8/배열에서문자열대소문자변환하기.ts
> +		return index % 2 === 1 ? string.toUpperCase() : string.toLowerCase();
[9929bd9](https://github.com/xxziiko/ts-snippets/pull/13/commits/9929bd944df7ef11d4e87c3038b7e39a5e31c564) 수정했습니다!

2024-06-25 05:33 UTC, xxziiko commented on week8/문자열이몇번등장하는지세기.ts
> +	return myString.substring(0, pat.length) === pat
[7e8559a](https://github.com/xxziiko/ts-snippets/pull/13/commits/7e8559a54d0c786fced0d903eb0ea005fae9fbec) 수정했습니다!

2024-06-25 05:33 UTC, xxziiko commented
@f-lab-jake 말씀주신 내용 수정했습니다!

2024-06-27 02:39 UTC, f-lab-jake approved these changes

2024-06-27 09:30 UTC, merged