[week10-1] 프로그래머스 알고리즘 풀이
xxziiko/Algorithm-Study pull request #16
Opened 2024-07-07 16:49 UTC by xxziiko

10주차 첫번째 알고리즘 풀이 입니다!
@f-lab-jake

2024-07-09 11:51 UTC, f-lab-jake requested changes

2024-07-09 11:51 UTC, f-lab-jake commented on week10/다음에올숫자.ts
> +	const commonDifference = common[1] - common[0];
destructuring을 써보세요

2024-07-09 11:51 UTC, f-lab-jake commented on week10/다항식더하기.ts
> +			sumCoefficientOfX += Number(term.replace("x", "")) || 1;
이건 `Number(빈문자열)` 하면 `NaN`이 나오고 거기 `|| 1`을하면 1이 되는 동작을 이용한 코드입니다.
실제로 하고 싶은건 빈문자열일때 1이 되는것인데 약간 다르죠?
그리고 `0x`의 경우에도 1이라고 뜨는 버그가 있습니다.

2024-07-09 11:51 UTC, f-lab-jake commented on week10/배열만들기5.ts
> +	});
`filter`를 쓰세요. 그게 왜 나을까요?

2024-07-09 11:51 UTC, f-lab-jake commented on week10/연속된수의합.ts
> +	const start = num % 2 === 1 ? Math.floor(num / 2) : Math.floor(num / 2) - 1;
`Math.floor(num / 2)`같은 계산을 2번 반복하지 마세요.

2024-07-09 11:51 UTC, f-lab-jake commented on week10/코드처리하기.ts
> +			else mode = 1;
한줄로 가능합니다.

2024-07-09 11:51 UTC, f-lab-jake commented on week10/코드처리하기.ts
> +			if (i % 2 === mode) ret += char;
else if  쓰세요.

2024-07-09 16:23 UTC, xxziiko commented on week10/배열만들기5.ts
> +	});
@f-lab-jake `flatMap` 은 반환되는 배열의 길이를 보장하지 않는다는 점, 그리고 `filter`와 `map`을 사용하는게 각각 어떤 일을 하고 있는지 더 명확하게 보이기 때문에 인 것 같습니다

2024-07-10 01:45 UTC, xxziiko commented on week10/다음에올숫자.ts
> +	const commonDifference = common[1] - common[0];
[2614dd7](https://github.com/xxziiko/ts-snippets/pull/16/commits/2614dd77f27b65d3f49411a9139b1916549a861e) 수정했습니다!

2024-07-10 01:45 UTC, xxziiko commented on week10/다항식더하기.ts
> +			sumCoefficientOfX += Number(term.replace("x", "")) || 1;
[1ab9a8b](https://github.com/xxziiko/ts-snippets/pull/16/commits/1ab9a8b9527a1de802b36688d1d14969e06af758) 수정했습니다!

2024-07-10 01:46 UTC, xxziiko commented on week10/배열만들기5.ts
> +	});
[5bf95c1](https://github.com/xxziiko/ts-snippets/pull/16/commits/5bf95c165ebc68cc8776d50b663b5df82841bbd2) 수정했습니다!

2024-07-10 01:46 UTC, xxziiko commented on week10/연속된수의합.ts
> +	const start = num % 2 === 1 ? Math.floor(num / 2) : Math.floor(num / 2) - 1;
[a226012](https://github.com/xxziiko/ts-snippets/pull/16/commits/a22601218c65d247ecafb14f7ad2871a39bff015) 수정했습니다!

2024-07-10 01:46 UTC, xxziiko commented on week10/코드처리하기.ts
> +			else mode = 1;
[a226012](https://github.com/xxziiko/ts-snippets/pull/16/commits/a22601218c65d247ecafb14f7ad2871a39bff015)수정했습니다!

2024-07-10 01:47 UTC, xxziiko commented
@f-lab-jake 멘토님 말씀주신 내용 수정했습니다!

2024-08-15 10:12 UTC, merged