[week10-2]프로그래머스 풀이
xxziiko/Algorithm-Study pull request #17
Opened 2024-07-09 16:05 UTC by xxziiko

10주차 2회차 알고리즘 풀이입니다!

@f-lab-jake

2024-07-14 14:08 UTC, f-lab-jake requested changes

2024-07-14 14:08 UTC, f-lab-jake commented on week10/등차수열의특정한항만더하기.ts
> +	for (const boolean of included) {
`boolean` -> `included`
`included` -> `includeds`하면 되겠네요.
`boolean`처럼 타입 이상의을 설명하지않는 변수명을 피하세요.

2024-07-14 14:08 UTC, f-lab-jake commented on week10/피로도.ts
> +}
요걸 제네레이터로 고쳐봅시다.

2024-07-15 07:33 UTC, xxziiko commented on week10/등차수열의특정한항만더하기.ts
> +	for (const boolean of included) {
[fb7fc7c](https://github.com/xxziiko/ts-snippets/pull/17/commits/fb7fc7ca6bdcbf35f087036c9ad458dd2aee93d6) 넵 수정했습니다!

2024-07-15 07:34 UTC, xxziiko commented on week10/피로도.ts
> +}
[f8b804f](https://github.com/xxziiko/ts-snippets/pull/17/commits/f8b804f114e5314ad27d8ac77c5a0dd631ca194d) 적용했습니다!

2024-07-15 07:34 UTC, xxziiko commented
@f-lab-jake 멘토님 말씀주신 내용 반영했습니다!

2024-07-15 09:07 UTC, f-lab-jake approved these changes

2024-07-15 13:53 UTC, f-lab-jake approved these changes

2024-07-15 14:52 UTC, merged