Week11
xxziiko/Algorithm-Study pull request #18
Opened 2024-07-15 14:49 UTC by xxziiko

@f-lab-jake
11주차 풀이입니다!

2024-07-16 02:27 UTC, f-lab-jake requested changes

2024-07-16 02:27 UTC, f-lab-jake commented on week11/뉴스클러스터링.ts
> +		const count1 = str1Map.get(key) || 0;
|| 대신 ??를 써야합니다. 이론상으론 성능에도 차이가 있습니다. 왜그럴까요?

2024-07-16 02:27 UTC, f-lab-jake commented on week11/타겟넘버.ts
> +	return dfs();
잘했습니다. 그런데 구조를 약간 고치면 `dfs`를 굳이 따로 안둬도 됩니다.

2024-07-16 05:00 UTC, xxziiko commented on week11/뉴스클러스터링.ts
> +		const count1 = str1Map.get(key) || 0;
아! key가 없을 때와 `value`가 0일 때 두가지 경우의 수가 있기 때문에 `||` 는 의도와 다른 값으로 반환이 될 수 있고, `value`가 0일 경우 불필요한 계산이 이루어집니다!

2024-07-16 05:17 UTC, xxziiko commented on week11/타겟넘버.ts
> +	return dfs();
@f-lab-jake [80a4a2d](https://github.com/xxziiko/ts-snippets/pull/18/commits/80a4a2da8fde086fa8038eb135b33a24d4a366c7) 다시 수정해봤습니다..!

2024-07-16 05:20 UTC, f-lab-jake requested changes

2024-07-16 05:20 UTC, f-lab-jake commented on week11/타겟넘버.ts
> +	sum = 0,
`index` 와 `sum` 없이도 됩니다

2024-07-16 05:57 UTC, xxziiko commented on week11/타겟넘버.ts
> +	sum = 0,
@f-lab-jake [2fdaed5](https://github.com/xxziiko/ts-snippets/pull/18/commits/2fdaed5e1c59ad3a57cc35fac6d65faffa70535d) sum은 잘 모르겠습니다..!!

2024-07-16 06:13 UTC, f-lab-jake requested changes

2024-07-16 06:13 UTC, f-lab-jake commented on week11/타겟넘버.ts
> +	const subtract = solution(numbers.slice(1), target, num - sum);
`sum`도 뺄수있어요

2024-07-16 06:14 UTC, f-lab-jake requested changes

2024-07-16 06:14 UTC, f-lab-jake commented on week11/타겟넘버.ts
> +	const num = numbers[0];
그리고 길이확인도 하기전부터 `[0]`을 하는건 위험합니다.

2024-07-16 13:10 UTC, xxziiko commented on week11/타겟넘버.ts
> +	const num = numbers[0];
앗 수정했습니다!

2024-07-19 01:36 UTC, f-lab-jake requested changes

2024-07-19 01:36 UTC, f-lab-jake commented on week11/뉴스클러스터링.ts
> +	const arr = [...xs];
generator를 쓴 의미가 없어지죠? 길이가 무한할 경우엔 크래시가 날겁니다.

2024-07-19 01:36 UTC, f-lab-jake commented on week11/뉴스클러스터링.ts
> +}
요건 `chunk`가 너무 많은 일을합니다. 그래서 막상 `generateBigrams`는 하는일이 없습니다. 이름에 맞는 작은일을 하도록 하세요.

2024-07-21 08:40 UTC, xxziiko commented on week11/뉴스클러스터링.ts
> +	const arr = [...xs];
@f-lab-jake 앗!! 다시 수정했습니다!

2024-07-21 08:40 UTC, xxziiko commented on week11/뉴스클러스터링.ts
> +}
다시 분리했습니다!

2024-07-22 02:01 UTC, f-lab-jake approved these changes
`chunk`의 가장 일반적인 타입은 `function* chunk<T>(size: number, xs: Iterable<T>): Iterable<Iterable<T>>`일 것입니다.
그런데 이 문제에선 string뱉는게 더 편하겠네요.

2024-07-22 05:56 UTC, merged