[week12] 프로그래머스 풀이
xxziiko/Algorithm-Study pull request #19
Opened 2024-07-23 07:47 UTC by xxziiko

12주차 알고리즘 풀이입니다!
@f-lab-jake

2024-07-23 13:28 UTC, f-lab-jake requested changes

2024-07-23 13:28 UTC, f-lab-jake commented on week12/9로나눈나머지.ts
> +	return sum % nine;
lodash `sum` 써보세요

2024-07-23 13:28 UTC, f-lab-jake commented on week12/k진수에서소수개수구하기.ts
> +		if (char !== "1" && checkPrime(Number(char).toString(10))) count++;
`char !== "1"`이 안 좋습니다. 왜그럴까요?

2024-07-23 13:28 UTC, f-lab-jake commented on week12/n진수게임.ts
> +	const gen = champernowneGen(n);
`gen`은 아무의미없는 변수명입니다. 형태는 어차피 타입에 나와있습니다. 어떤값이 있는지를 설명하세요.

2024-07-23 13:28 UTC, f-lab-jake commented on week12/게임맵최단거리.ts
> +function solution(maps: [number, number, number, number, number][]) {
길이 5란 사실을 사용할게 아니면 타입을 이렇게 하면 안됩니다.

2024-07-23 13:28 UTC, f-lab-jake commented on week12/게임맵최단거리.ts
> +			if (row === rowLen - 1 && col === colLen - 1) return distance;
`rowLen - 1`같은걸 미리해놓으세요. 이름은 `goal`정도가 좋겠네요.

2024-07-23 13:28 UTC, f-lab-jake commented on week12/모음사전.ts
> +		if (currentWord.length > 5) return;
이런 로직 없이도 잘돌아가야합니다. 특별한 경우가 아니면 있을 필요도 없고요.

2024-07-23 13:28 UTC, f-lab-jake commented on week12/모음사전.ts
> +	function dfs(currentWord = "") {
generator써봅시다.

2024-07-25 05:31 UTC, xxziiko commented on week12/모음사전.ts
> +	function dfs(currentWord = "") {
[806b78f](https://github.com/xxziiko/ts-snippets/pull/19/commits/806b78f9f0139715352867c5554328b1679ed10a) 수정했습니다!

2024-07-25 05:32 UTC, xxziiko commented on week12/n진수게임.ts
> +	const gen = champernowneGen(n);
[fdb802d](https://github.com/xxziiko/ts-snippets/pull/19/commits/fdb802d52da67bde135bae2afebd38c95983712c) 수정했습니다!

2024-07-25 05:33 UTC, xxziiko commented on week12/9로나눈나머지.ts
> +	return sum % nine;
[0f28aed](https://github.com/xxziiko/ts-snippets/pull/19/commits/0f28aed1caea18696d0aa6367984484d453c0a09) 수정했습니다!

2024-07-25 05:34 UTC, xxziiko commented on week12/게임맵최단거리.ts
> +function solution(maps: [number, number, number, number, number][]) {
@f-lab-jake 튜플인 경우를 제외하고는 `number[][]` 으로 표현하라는 말씀이실까요?!

2024-07-25 05:35 UTC, xxziiko commented on week12/k진수에서소수개수구하기.ts
> +		if (char !== "1" && checkPrime(Number(char).toString(10))) count++;
@f-lab-jake 잘 모르겠습니다..!

2024-07-25 05:36 UTC, xxziiko commented
@f-lab-jake 멘토님 피드백 주신 내용 반영했습니다!

2024-07-25 06:07 UTC, f-lab-jake requested changes

2024-07-25 06:07 UTC, f-lab-jake commented on week12/모음사전.ts
>  	}
줄일수있죠?

2024-07-26 06:41 UTC, xxziiko commented on week12/모음사전.ts
>  	}
@f-lab-jake  수정했습니다!!

2024-07-27 02:15 UTC, f-lab-jake approved these changes

2024-07-27 02:16 UTC, f-lab-jake commented on week12/모음사전.ts
>  	}
컴퓨터한테 뭘 해야할지 명령을 내리는 식으로 생각하지말고, 값을 기준으로 어떤값이 필요하고 어떻게 변형해야하는지를 생각합시다. 그러면 고친 코드가 자연스럽게 떠오릅니다.

2024-07-27 05:10 UTC, xxziiko commented on week12/모음사전.ts
>  	}
아하,, 알겠습니다!

2024-07-27 05:11 UTC, merged