[Week2] 프로그래머스 lv.2 5문제
xxziiko/Algorithm-Study pull request #2
Opened 2024-05-10 13:46 UTC by xxziiko

프로그래머스 lv.2 5문제입니다

@f-lab-jake

2024-05-12 06:12 UTC, f-lab-jake requested changes

2024-05-12 06:12 UTC, f-lab-jake commented on week2/구명보트.js
> +		}
중복을 제거하세요

2024-05-12 06:12 UTC, f-lab-jake commented on week2/귤_고르기.js
> +		if (sum >= k) return sortedList.slice(0, i).length;
`slice`를 꼭 써야하나요?

2024-05-12 06:12 UTC, f-lab-jake commented on week2/귤_고르기.js
> +	for (const item of tangerine) map.set(item, (map.get(item) || 0) + 1);
`??`를 사용하세요

2024-05-12 06:12 UTC, f-lab-jake commented on week2/귤_고르기.js
> +	for (const item of tangerine) map.set(item, (map.get(item) || 0) + 1);
왜그럴까요?

2024-05-12 06:12 UTC, f-lab-jake commented on week2/영어_끝말잇기.js
> +		} else number++;
`number = 1`대신 `number = 0`을 쓰고, 코드를 거기맞춰 고쳐보세요.

2024-05-12 06:12 UTC, f-lab-jake commented on week2/영어_끝말잇기.js
> +	for (let i = 0; i < words.length; i++) {
for of 쓰세요

2024-05-12 06:12 UTC, f-lab-jake commented on week2/영어_끝말잇기.js
> +	for (let i = 0; i < words.length; i++) {
인덱스가 필요할땐 `Array.entries`를 쓰세요.

2024-05-12 06:12 UTC, f-lab-jake commented on week2/점프와_순간이동.js
> +	}
재귀호출로 다시 짜보세요

2024-05-12 08:53 UTC, xxziiko commented on week2/귤_고르기.js
> +	for (const item of tangerine) map.set(item, (map.get(item) || 0) + 1);
undefined나 null 일 때 우변을 반환하는 `??` 에 비해 `||`는 falsy한 값(null, undefined, 0, '', false, NaN 등)일 때 반환이 되기 때문에 `??`가 자유도가 낮아 버그 확률이 낮습니다..!

2024-05-12 08:56 UTC, xxziiko commented on week2/구명보트.js
> +		}
[0fd6791](https://github.com/xxziiko/ts-snippets/pull/2/commits/0fd6791736dfce572d7fc5274d436641b131e604) 수정했습니다!

2024-05-12 08:57 UTC, xxziiko commented on week2/귤_고르기.js
> +		if (sum >= k) return sortedList.slice(0, i).length;
[0fd6791](https://github.com/xxziiko/ts-snippets/pull/2/commits/0fd6791736dfce572d7fc5274d436641b131e604) count 변수를 두어 수정했습니다!

2024-05-12 08:58 UTC, xxziiko commented on week2/구명보트.js
> +		}
[0fd6791](https://github.com/xxziiko/ts-snippets/pull/2/commits/0fd6791736dfce572d7fc5274d436641b131e604) 수정했습니다!

2024-05-12 08:59 UTC, xxziiko commented on week2/귤_고르기.js
> +	for (const item of tangerine) map.set(item, (map.get(item) || 0) + 1);
[00f8983](https://github.com/xxziiko/ts-snippets/pull/2/commits/00f8983817833452dce31f479ee87abbdf57fe12) 수정했습니다!

2024-05-12 08:59 UTC, xxziiko commented on week2/귤_고르기.js
> +		if (sum >= k) return sortedList.slice(0, i).length;
count 변수를 두는 것으로 수정했습니다!

2024-05-12 09:00 UTC, xxziiko commented on week2/영어_끝말잇기.js
> +		} else number++;
[7e36478](https://github.com/xxziiko/ts-snippets/pull/2/commits/7e3647836cee9d701dccd14b4f6dbbbf0a6d5124) 수정했습니다!

2024-05-12 09:00 UTC, xxziiko commented on week2/점프와_순간이동.js
> +	}
[8f65ddb](https://github.com/xxziiko/ts-snippets/pull/2/commits/8f65ddb0b6407d98a12f789e06efa952462062e6) 수정했습니다!

2024-05-12 09:00 UTC, xxziiko commented on week2/영어_끝말잇기.js
> +	for (let i = 0; i < words.length; i++) {
[7e36478](https://github.com/xxziiko/ts-snippets/pull/2/commits/7e3647836cee9d701dccd14b4f6dbbbf0a6d5124) 수정했습니다!

2024-05-12 09:02 UTC, xxziiko commented
@f-lab-jake  피드백 해주신 내용 반영하여 수정 완료했습니다!!

2024-05-13 03:07 UTC, f-lab-jake requested changes

2024-05-13 03:07 UTC, f-lab-jake commented on week2/점프와_순간이동.js
> +const countDivide = (k, n) => {
k를 쓰지마세요. 인자는 n하나로 족합니다.

2024-05-13 03:07 UTC, f-lab-jake commented on week2/영어_끝말잇기.js
> +	const usedWord = [];
`usedWords`로 쓰세요. 배열 등은 복수형으로 써줍시다.

2024-05-13 11:44 UTC, xxziiko commented on week2/영어_끝말잇기.js
> +	const usedWord = [];
[b93c59e](https://github.com/xxziiko/ts-snippets/pull/2/commits/b93c59e6c89cb3a564a7318fa7f9976a190aba6d)수정했습니다!

2024-05-13 11:45 UTC, xxziiko commented on week2/점프와_순간이동.js
> +const countDivide = (k, n) => {
[0fcbd0b](https://github.com/xxziiko/ts-snippets/pull/2/commits/0fcbd0be0d699f24e4e5f401901baba657aed54b)수정했습니다!

2024-05-13 11:45 UTC, xxziiko commented
@f-lab-jake 피드백 주신 내용 수정했습니다!

2024-05-14 02:14 UTC, f-lab-jake approved these changes

2024-05-14 02:18 UTC, merged