[week13] 프로그래머스 알고리즘 풀이
xxziiko/Algorithm-Study pull request #20
Opened 2024-07-27 07:34 UTC by xxziiko

@f-lab-jake

1. 뒤에있는 큰 수 찾기 - 시간초과
2. 방문 길이 - 중복 방문 거리 계산 로직 모르겠습니다!

2024-08-02 05:46 UTC, xxziiko commented
@f-lab-jake 멘토님 혹시 누락되었을까요!?

2024-08-02 05:54 UTC, f-lab-jake requested changes

2024-08-02 05:54 UTC, f-lab-jake commented on week13/간단한식계산하기.ts
> +	return result;
그냥 바로 리턴합시다.
이유없는 코드는 끝까지 줄여보세요. 여기서 할당하려고하다보니 맨위에 `result = 0`이라는 아무 근거없는 코드를 쓰게되었습니다.

2024-08-02 05:54 UTC, f-lab-jake commented on week13/뒤에있는큰수찾기.ts
> +			result.push(findIndex);
`findIndex`대신 -`을 쓰는게 낫습니다. 왜일까요?

2024-08-02 05:54 UTC, f-lab-jake commented on week13/문자개수세기.ts
> +		const isUpper = charCode >= charCode_A && charCode <= charCode_Z;
암호 문제에서처럼 `baseChar`라는 변수를 도입해보세요.

2024-08-02 05:54 UTC, f-lab-jake commented on week13/문자개수세기.ts
> +			? charCode % charCode_A
%는 정확하지 않죠? 빼는게 맞습니다.

2024-08-02 06:30 UTC, xxziiko commented on week13/뒤에있는큰수찾기.ts
> +			result.push(findIndex);
@f-lab-jake  -` 이게뭘까요..?!

2024-08-02 06:30 UTC, xxziiko commented
@f-lab-jake 말씀주신 내용 수정했습니다!

2024-08-04 05:03 UTC, f-lab-jake requested changes

2024-08-04 05:03 UTC, f-lab-jake commented on week13/뒤에있는큰수찾기.ts
> +			result.push(findIndex);
-1을 잘못쳤네요

2024-08-04 10:57 UTC, xxziiko commented on week13/뒤에있는큰수찾기.ts
> +			result.push(findIndex);
@f-lab-jake  앗 `findIndex'를 그대로 `push` 하면 `findIndex` 값이 뭔지 한 번 더 생각하게 해서일까요?

2024-08-05 02:03 UTC, f-lab-jake commented on week13/뒤에있는큰수찾기.ts
> +			result.push(findIndex);
네네. 문제에 -1 넣으라고 되있을겁니다. 그러면 그냥 -1이라고 쓰면되죠.

2024-08-05 02:03 UTC, f-lab-jake approved these changes

2024-08-11 04:49 UTC, merged