[week13-2] 프로그래머스 알고리즘 풀이
xxziiko/Algorithm-Study pull request #21
Opened 2024-08-06 07:02 UTC by xxziiko

@f-lab-jake

2024-08-12 02:03 UTC, f-lab-jake requested changes

2024-08-12 02:03 UTC, f-lab-jake commented on week13/겹치는선분의길이.ts
> +	}
이부분이 좀 이해하기가 어려운데요.
사실 요부분만 개선하면 선분의 갯수가 3이아니라 임의의 n일때도 프로그램이 맞도록 만들수있습니다. 그렇게 고쳐볼까요? 도전과제 느낌입니다.

2024-08-12 02:03 UTC, f-lab-jake commented on week13/다트게임.ts
> +	for (const char of dartResult) {
https://f-lab.kr/blog/how-good-algorithmic-solution
요글을 참고해서 리팩토링해보세요.

2024-08-12 02:03 UTC, f-lab-jake commented on week13/주식가격.ts
> +	function dfs(prices: number[]) {
dfs가 맞는 접근일까요?

2024-08-16 10:34 UTC, xxziiko commented on week13/겹치는선분의길이.ts
> +	}
[97b8b5c](https://github.com/xxziiko/programmers-algorithm/pull/21/commits/97b8b5c9fd87534470d81074e50ae57c8da100ed) @f-lab-jake 멘토님, 수정해 보았습니다!

2024-08-17 06:24 UTC, f-lab-jake requested changes

2024-08-17 06:24 UTC, f-lab-jake commented on week13/겹치는선분의길이.ts
>  	}
틀린 코드같은데 반례를 스스로 만들어보세요.

2024-08-18 06:59 UTC, f-lab-jake approved these changes

2024-08-27 16:26 UTC, merged