[week16] 프로그래머스 알고리즘 풀이
xxziiko/Algorithm-Study pull request #23
Opened 2024-08-27 07:59 UTC by xxziiko

이번주 알고리즘 풀이입니다!
@f-lab-jake

2024-08-27 10:26 UTC, f-lab-jake requested changes

2024-08-27 10:26 UTC, f-lab-jake commented on week13/겹치는선분의길이.ts
> +	if (!overlaps.length) return 0;
요게 없어도 답이 나오겠죠?

2024-08-27 10:26 UTC, f-lab-jake commented on week16/대충만든자판.ts
> +			map.set(char, Math.min(map.get(char) ?? Number.POSITIVE_INFINITY, i + 1));
`Number.POSITIVE_INFINITY` 요런 트릭 안쓰는게 좋습니다. 읽는사람한테 한번더 생각하게 만듭니다. 그냥 정직하게 분기해서쓰면 생각은 덜합니다.

2024-08-27 10:26 UTC, f-lab-jake commented on week16/체육복.ts
> +	const realReserve = reserve.sort().filter((r) => !losts.includes(r));
요거를 하는 함수가 Lodash에 있습니다.

2024-08-27 16:26 UTC, xxziiko commented
@f-lab-jake 말씀주신 내용 수정했습니다!

2024-08-29 04:15 UTC, f-lab-jake requested changes

2024-08-29 04:15 UTC, f-lab-jake commented on week16/대충만든자판.ts
> +			if (map.has(char)) map.set(char, Math.min(map.get(char), i + 1));
`has`랑 `get`을 동시에 쓰지마세요.

2024-08-29 05:17 UTC, xxziiko commented on week16/대충만든자판.ts
> +			if (map.has(char)) map.set(char, Math.min(map.get(char), i + 1));
@f-lab-jake 수정했습니다!

2024-08-30 03:12 UTC, f-lab-jake requested changes

2024-08-30 03:12 UTC, f-lab-jake commented on week16/대충만든자판.ts
> +			if (getItem) map.set(char, Math.min(getItem, i + 1));
1. `getItem`란 이름은 함수같네요.
2. 기계적으로 그냥 `has`를 빼기만하는게 아니라 그걸 토대로 더 나은 패턴을 찾으란 얘기입니다.

2024-08-31 04:03 UTC, xxziiko commented on week16/대충만든자판.ts
> +			if (getItem) map.set(char, Math.min(getItem, i + 1));
@f-lab-jake 수정했습니다!

2024-09-01 11:21 UTC, f-lab-jake approved these changes

2024-09-01 11:21 UTC, f-lab-jake commented
꼭 변수로 만들필욘없고(이름짓기가 어려우니) 그냥 인라이닝해도 됩니다.

2024-09-05 05:49 UTC, merged