[week4] 프로그래머스 lv.1 풀이입니다!
xxziiko/Algorithm-Study pull request #5
Opened 2024-05-26 06:26 UTC by xxziiko

@f-lab-jake

2024-05-27 02:45 UTC, f-lab-jake requested changes

2024-05-27 02:45 UTC, f-lab-jake commented on week4/시저암호.ts
> +			ASCII = 97 + (ASCII - 123);
65, 90 이런 숫자들을 magic number라고 합니다. magic number에 대해 알아보세요.
그리고 없애보세요.

2024-05-27 02:45 UTC, f-lab-jake commented on week4/최소직사각형.ts
> +		if (maxHeight < size[1]) maxHeight = size[1];
`size`같은 튜플에 대해 indexing을 하지 마세요.

2024-05-27 02:45 UTC, f-lab-jake commented on week4/크기가작은부분문자열.ts
> +		if (+window <= +p) count++;
`+window`같은건 암시적이라서 안좋습니다.
진작에 숫자로 바꿔 놓으면 됩니다.

2024-05-27 02:45 UTC, f-lab-jake commented on week4/크기가작은부분문자열.ts
> +	}
잘했습니다 .그런데 그냥 for문을 쓰세요. 이 경우엔 굳이 iterator protocol을 사용해서 어렵게 할 필요가 없습니다.

2024-05-27 02:45 UTC, f-lab-jake commented on week4/프로세스.ts
> +		};
의미가 이해가 안됩니다

2024-05-27 02:45 UTC, f-lab-jake commented on week4/비밀지도.ts
> +};
함수로 잘 뺐습니다.

2024-05-27 02:45 UTC, f-lab-jake commented on week4/비밀지도.ts
> +	const replaceArr2 = replaceString(n, arr2);
`map1` `map2`가 낫겠죠?

2024-05-27 02:45 UTC, f-lab-jake commented on week4/비밀지도.ts
> +	for (const [i, string] of replaceArr1.entries()) {
`zip`을 쓰세요

2024-05-27 02:45 UTC, f-lab-jake commented on week4/두개뽑아서더하기.ts
> +	}
`entries`를 활용해보세요.

2024-05-27 12:30 UTC, xxziiko commented on week4/시저암호.ts
> +			ASCII = 97 + (ASCII - 123);
[299934d](https://github.com/xxziiko/ts-snippets/pull/5/commits/299934d9633ddf29b07496beba5f2570865df11d) 수정했습니다!

2024-05-27 12:30 UTC, xxziiko commented on week4/최소직사각형.ts
> +		if (maxHeight < size[1]) maxHeight = size[1];
[81d7758](https://github.com/xxziiko/ts-snippets/pull/5/commits/81d77580ab971aa10ec0e5c28698ec3ab84c53b5) 수정했습니다!

2024-05-27 12:31 UTC, xxziiko commented on week4/크기가작은부분문자열.ts
> +		if (+window <= +p) count++;
[8c3c0b0](https://github.com/xxziiko/ts-snippets/pull/5/commits/8c3c0b016404d771e00820b3e11fe95fd2588011) 수정했습니다!

2024-05-27 12:31 UTC, xxziiko commented on week4/크기가작은부분문자열.ts
> +	}
[8c3c0b0](https://github.com/xxziiko/ts-snippets/pull/5/commits/8c3c0b016404d771e00820b3e11fe95fd2588011) 수정했습니다!

2024-05-27 12:32 UTC, xxziiko commented on week4/비밀지도.ts
> +	const replaceArr2 = replaceString(n, arr2);
[423ab2e](https://github.com/xxziiko/ts-snippets/pull/5/commits/423ab2e549ab0d1dcd7ce5352e2bb68255bffe49) 수정했습니다!

2024-05-27 12:32 UTC, xxziiko commented on week4/비밀지도.ts
> +	for (const [i, string] of replaceArr1.entries()) {
[423ab2e](https://github.com/xxziiko/ts-snippets/pull/5/commits/423ab2e549ab0d1dcd7ce5352e2bb68255bffe49) 수정했습니다!

2024-05-27 12:32 UTC, xxziiko commented on week4/두개뽑아서더하기.ts
> +	}
[61520ab](https://github.com/xxziiko/ts-snippets/pull/5/commits/61520ab88ffc00f6f95f055450ffd1f00de83d37) 수정했습니다!

2024-05-27 12:37 UTC, xxziiko commented on week4/프로세스.ts
> +		};
[42ad8f1](https://github.com/xxziiko/ts-snippets/pull/5/commits/42ad8f1f4b02a05ac6a3474ed5ce0dbe846dddde) 수정했습니다!

2024-05-27 12:38 UTC, xxziiko commented
@f-lab-jake 피드백 반영하여 수정했습니다!

2024-05-28 03:04 UTC, f-lab-jake commented on week4/프로세스.ts
> +		if (!current) break;
기존코드도 답은 맞게 나왔던거겠죠?
기존코드는 어떤 동작에 의존하고 있었나요?

2024-05-28 03:05 UTC, f-lab-jake requested changes

2024-05-28 03:05 UTC, f-lab-jake commented on week4/두개뽑아서더하기.ts
> +			if (i < j) set.add(num1 + num2);
이러면 동작이 달라진거죠. 기존 동자을 유지해야합니다.

2024-05-28 03:05 UTC, f-lab-jake commented on week4/두개뽑아서더하기.ts
> +			if (i < j) set.add(num1 + num2);
`slice`를 활용하세요.

2024-05-28 03:05 UTC, f-lab-jake requested changes

2024-05-28 03:05 UTC, f-lab-jake commented on week4/최소직사각형.ts
> +		if (maxHeight < height) maxHeight = height;
`Math.max`를 활용하세요.

2024-05-28 07:25 UTC, xxziiko commented on week4/프로세스.ts
> +		if (!current) break;
@f-lab-jake 네, 기존 코드는 current가 undefined 일 수 있다는 타입에러가 있어서 current에 초기화 할때 ?? 연산자로 초기화를 하려던 의도였는데, 근본적인 해결이 아니었기에 불필요한 코드를 없애고 다시 접근했습니다..!

2024-05-28 07:45 UTC, xxziiko commented on week4/최소직사각형.ts
> +		if (maxHeight < height) maxHeight = height;
[8cc1619](https://github.com/xxziiko/ts-snippets/pull/5/commits/8cc1619c02326ba4f4134efd50646225425bb40d) 수정했습니다!

2024-05-28 07:45 UTC, xxziiko commented on week4/두개뽑아서더하기.ts
> +			if (i < j) set.add(num1 + num2);
[757e14d](https://github.com/xxziiko/ts-snippets/pull/5/commits/757e14d4baace4dc668271523f2b414ce50f4b04) 수정했습니다!

2024-05-28 07:46 UTC, xxziiko commented
@f-lab-jake 피드백 주신 내용 수정했습니다!

2024-05-28 11:44 UTC, f-lab-jake commented on week4/프로세스.ts
> +		if (!current) break;
> 기존코드는 어떤 동작에 의존하고 있었나요?

요 질문은 안좋은 코드인데도 어찌저찌 답은 내고 있었잖아요? 그 원리가 뭐냐는 질문입니다.

2024-05-28 13:00 UTC, xxziiko commented on week4/프로세스.ts
> +		if (!current) break;
@f-lab-jake ?? 연산자 뒤로 넘어갈 일이 없어서 오류 없이 동작 되었다고 생각했습니다

2024-05-29 03:22 UTC, f-lab-jake requested changes

2024-05-29 03:22 UTC, f-lab-jake commented on week4/시저암호.ts
> +			ASCII = ASCII_a + (ASCII - (ASCII_z + 1));
코드를 개선하세요

2024-05-30 01:46 UTC, xxziiko commented on week4/시저암호.ts
> +			ASCII = ASCII_a + (ASCII - (ASCII_z + 1));
@f-lab-jake 수정했습니다!!

2024-05-30 02:43 UTC, f-lab-jake requested changes

2024-05-30 02:43 UTC, f-lab-jake commented on week4/시저암호.ts
> +};
일단 잘했습니다. 그런데 여기까지한 리팩토링은 코드의 똑같은 모양을 눈으로보고 분리한겁니다.
여전히 뭘 분리한건지 이해는 못한상태입니다. 그건 함수의 인자명을 보면 알수있습니다.
의미가 있는 인자명을 주어야 정확히 무슨 로직을 분리한건지 이해한상태가 됩니다.

2024-05-30 06:57 UTC, xxziiko commented on week4/시저암호.ts
> +};
@f-lab-jake 다시 수정했습니다!!

2024-05-30 07:23 UTC, f-lab-jake requested changes
좀더 고민해보세요.

2024-05-30 07:23 UTC, f-lab-jake commented on week4/시저암호.ts
> +const getASCIICode = (
일단 이름이 `getASCIIICode`인것부터 문제입니다. 그냥 무슨 아스키코드를 받을수있는건 아는데, 그게 뭔지 알수가 없죠.

좀더 생각해보고 안되겠으면 다음 멘토링에 얘기합시다.

2024-05-31 06:19 UTC, xxziiko commented on week4/시저암호.ts
> +const getASCIICode = (
@f-lab-jake 넵..! 한번 더 수정 해보았습니다!

2024-06-06 02:42 UTC, xxziiko commented on week4/시저암호.ts
> +const getASCIICode = (
[571cf33](https://github.com/xxziiko/ts-snippets/pull/5/commits/571cf339390e92ebbf0ef02df05f40d5555a8929) @f-lab-jake 멘토님 말씀해주신 내용으로 수정했습니다!!

2024-06-07 03:10 UTC, f-lab-jake requested changes

2024-06-07 03:10 UTC, f-lab-jake commented on week4/시저암호.ts
> +		if (char !== " ")
요건 위치가 안좋습니다. 위치를 옮겨서 개선할 수 있습니다.

2024-06-07 03:10 UTC, f-lab-jake commented on week4/시저암호.ts
> +			result += String.fromCharCode(baseCharCode + ((index + n) % 26));
26도 제거해보세요

2024-06-07 03:10 UTC, f-lab-jake commented on week4/시저암호.ts
> +			result += String.fromCharCode(baseCharCode + ((index + n) % 26));
magic number를 없애란 얘기입니다.

2024-06-07 06:11 UTC, xxziiko commented on week4/시저암호.ts
> +			result += String.fromCharCode(baseCharCode + ((index + n) % 26));
@f-lab-jake  앗!! 다시 수정했습니다!
[eae5f75](https://github.com/xxziiko/ts-snippets/pull/5/commits/eae5f754eb8f9e2dfa45e8467df3a78f9ecbb55f)

2024-06-08 07:23 UTC, f-lab-jake requested changes

2024-06-08 07:23 UTC, f-lab-jake commented on week4/시저암호.ts
> +	const ALPHABET_COUNT = 26;
`ASCII_Z - ASCII_A + 1` 해도 됩니다.

2024-06-08 07:23 UTC, f-lab-jake commented on week4/시저암호.ts
> +				: char;
이렇게만 바꾸라고 하진 않겠죠?. `char`가 공백인 경우에 프로그램이 어떻게 돌아가는지 생각해보세요.

2024-06-08 12:51 UTC, xxziiko commented on week4/시저암호.ts
> +				: char;
@f-lab-jake 다시 수정했습니다!!

2024-06-09 14:37 UTC, f-lab-jake approved these changes

2024-06-10 05:20 UTC, merged