[week4-1] 프로그래머스 lv.1 풀이
xxziiko/Algorithm-Study pull request #7
Opened 2024-05-28 13:10 UTC by xxziiko

4주차 프로그래머스 lv.1 풀이 보충입니다!

@f-lab-jake

2024-05-29 03:23 UTC, f-lab-jake requested changes

2024-05-29 03:23 UTC, f-lab-jake commented on week4/k번째수.ts
> +	for (let i = 0; i < commands.length; i++) {
`i`가 필요없죠?
일단 `for  ... of` 를 쓴다음에 인덱스가 필요하면 바꿔야하지 반대가 되면 안됩니다.

2024-05-29 04:25 UTC, xxziiko commented on week4/k번째수.ts
> +	for (let i = 0; i < commands.length; i++) {
@f-lab-jake 수정했습니다!

2024-05-29 04:34 UTC, f-lab-jake approved these changes

2024-05-29 04:34 UTC, f-lab-jake commented on week4/k번째수.ts
> +	for (const command of commands) {
사실 여기서 바로 destructuring할수도 있습니다.

2024-05-29 04:39 UTC, xxziiko commented on week4/k번째수.ts
> +	for (const command of commands) {
@f-lab-jake 앗!! 수정했습니다!

2024-05-30 02:43 UTC, f-lab-jake approved these changes

2024-05-30 06:44 UTC, merged