[week5] 프로그래머스 lv.1 풀이
xxziiko/Algorithm-Study pull request #8
Opened 2024-06-02 15:48 UTC by xxziiko

[week5] 프로그래머스 lv.1 풀이 입니다!
@f-lab-jake

2024-06-03 03:16 UTC, f-lab-jake requested changes

2024-06-03 03:16 UTC, f-lab-jake commented on week5/2016년.ts
> +	return WEEKDAY[findIndex];
잘했습니다. 그런데 `Date`쓰지말고 다시해보세요.

2024-06-03 03:16 UTC, f-lab-jake commented on week5/기사단원의무기.ts
> +				if (j !== Math.floor(i / j)) count++;
`floor`가 필요한가요?

2024-06-03 03:16 UTC, f-lab-jake commented on week5/덧칠하기.ts
> +const fillArray = (num: number) => {
일단 이름이 거짓말입니다. `false`로 채우는건데 왜 그냥 `fillArray`인가요?
`true`로 채워야할일이 생기면 어떻게 할건가요?

문제는 너무 사소한 함수를 굳이한번더 감싸려고해서 생긴일입니다. 그냥 풀어서 써도 됩니다.

2024-06-03 03:16 UTC, f-lab-jake commented on week5/덧칠하기.ts
> +const fillArray = (num: number) => {
또는 `false`로 초기화하는 동작에 이름을 잘 붙이면됩니다.

2024-06-03 03:16 UTC, f-lab-jake commented on week5/모의고사.ts
> +	return scores.reduce<number[]>((result, score, index) => {
`result`를 수정하지마세요. 그냥 for문을 써도됩니다. 또는 `flatMap`을 써보세요.

2024-06-03 10:15 UTC, xxziiko commented on week5/기사단원의무기.ts
> +				if (j !== Math.floor(i / j)) count++;
[9c79d1b](https://github.com/xxziiko/ts-snippets/pull/8/commits/9c79d1bd82009fe3ffdcf476a1e45051e9cde3e2) 수정했습니다!

2024-06-03 10:15 UTC, xxziiko commented on week5/덧칠하기.ts
> +const fillArray = (num: number) => {
[cb90851](https://github.com/xxziiko/ts-snippets/pull/8/commits/cb90851e33ac8350345002e2f9b349d5f651c276) 수정했습니다!

2024-06-03 10:16 UTC, xxziiko commented on week5/모의고사.ts
> +	return scores.reduce<number[]>((result, score, index) => {
[1d43403](https://github.com/xxziiko/ts-snippets/pull/8/commits/1d4340341e98b1e7236e69af1ccc864381e50cbb) 수정했습니다!

2024-06-03 10:16 UTC, xxziiko commented on week5/2016년.ts
> +	return WEEKDAY[findIndex];
[f5587a8](https://github.com/xxziiko/ts-snippets/pull/8/commits/f5587a83053af6008f193d5adae46077e81c0df5) 수정했습니다!

2024-06-03 10:17 UTC, xxziiko commented
@f-lab-jake  멘토님 피드백 반영하여 수정 했습니다!!

2024-06-03 12:42 UTC, f-lab-jake requested changes

2024-06-03 12:42 UTC, f-lab-jake commented on week5/2016년.ts
> +	const index = (sum % 7 || WEEKDAY.length) - 1;
센스있게 잘했습니다. 근데 요렇게 쓸거면 7도 `WEEKDAY.length`로 바꿔야겠죠?

2024-06-03 12:42 UTC, f-lab-jake commented on week5/모의고사.ts
> +		if (el === max) return index + 1;
음 이 코드가 돌아가나요?

2024-06-03 12:42 UTC, f-lab-jake commented on week5/모의고사.ts
> +		if (el === max) return index + 1;
`flatMap`설명을 다시 읽어보세요.

2024-06-03 13:46 UTC, xxziiko commented on week5/2016년.ts
> +	const index = (sum % 7 || WEEKDAY.length) - 1;
[d2f98e5](https://github.com/xxziiko/ts-snippets/pull/8/commits/d2f98e5db639bc76540277fbd559a00f51584915) 수정했습니다!!

2024-06-03 13:47 UTC, xxziiko commented on week5/모의고사.ts
> +		if (el === max) return index + 1;
@f-lab-jake 엇,, 테스트 케이스 통과하긴 했는데 혹시 이렇게 수정하라는 말씀이었을까요? [7fb865f](https://github.com/xxziiko/ts-snippets/pull/8/commits/7fb865f81727c13a40c6b0ded06f3e2750a9853d)

2024-06-04 01:33 UTC, f-lab-jake approved these changes

2024-06-04 01:35 UTC, f-lab-jake commented on week5/모의고사.ts
> +		if (el === max) return index + 1;
아..`flatMap`이 배열아닌걸 리턴하면 자동으로 감싸주는 모양이네요. 안 좋은 동작입니다. 그런거에 의존하지 않는게 좋습니다.

그럼 왜 이경우에 `flatMap`이 쓸만한지 설명할수있을까요?

2024-06-04 13:37 UTC, xxziiko commented on week5/모의고사.ts
> +		if (el === max) return index + 1;
@f-lab-jake 일단 가독성면에서 `flatMap`이 더 간결하기 때문에 가독성이 높은 것 같고, 
`reduce`는 누적값을 계산하기 때문에 상대적으로 비용이 높은데 누적값을 계산하는 적절한 쓰임은 아니었기 때문에 `flatMap`을 사용하여 조건에 맞지 않는 요소를 제거하고 반환하는 게 적절한 것 같습니다..!!

2024-06-07 06:11 UTC, merged