[week6] 프로그래머스 lv.1 풀이
xxziiko/Algorithm-Study pull request #9
Opened 2024-06-08 12:55 UTC by xxziiko

@f-lab-jake
6주차 알고리즘 풀이 입니다!

2024-06-09 14:42 UTC, f-lab-jake requested changes

2024-06-09 14:42 UTC, f-lab-jake commented on week6/마지막두원소.ts
> +	const secondLastElement = num_list[num_list.length - 2];
`at` 쓰세요

2024-06-09 14:42 UTC, f-lab-jake commented on week6/문자열나누기.ts
> +	let lastCharCount = 0;
변수명이 왜 `firstCharCount`, `lastCharCount`인가요?

2024-06-09 14:42 UTC, f-lab-jake commented on week6/문자열나누기.ts
> +	if (firstCharCount !== 0 || lastCharCount !== 0) count++;
좀더 잘짜보세요.
일단 `firstChar`를 초기화하는 로직이 중복되어있습니다.

2024-06-09 14:42 UTC, f-lab-jake commented on week6/홀짝에따라다른값반환하기.ts
> +		if (n % 2 === 0 && i % 2 === 0) result += i * i;
조건문을 좀더 간결하게 만들어보세요. 안해도되는 연산을 하고있습니다.

2024-06-09 14:42 UTC, f-lab-jake commented on week6/옹알이_2.ts
> +	}
좀더 잘짜봅시다.

2024-06-10 08:35 UTC, xxziiko commented on week6/마지막두원소.ts
> +	const secondLastElement = num_list[num_list.length - 2];
[10d77b4](https://github.com/xxziiko/ts-snippets/pull/9/commits/10d77b4e616bcb858dcd2192b8a3ab2be88b5a93) 수정했습니다!

2024-06-10 08:36 UTC, xxziiko commented on week6/문자열나누기.ts
> +	let lastCharCount = 0;
첫번째문자열 count와 나머지문자열 count를 의도했던 건데 의미가 명확하지 못한 것 같아 다시 수정했습니다!

2024-06-10 08:37 UTC, xxziiko commented on week6/문자열나누기.ts
> +	if (firstCharCount !== 0 || lastCharCount !== 0) count++;
[beaa30c](https://github.com/xxziiko/ts-snippets/pull/9/commits/beaa30c8152c1cdf23ec41dda9d60602cfa625a2) 다시 수정했습니다!!

2024-06-10 08:37 UTC, xxziiko commented on week6/홀짝에따라다른값반환하기.ts
> +		if (n % 2 === 0 && i % 2 === 0) result += i * i;
[347926d](https://github.com/xxziiko/ts-snippets/pull/9/commits/347926d7d0d71b6c52584ba56ee688fd9a78a70b) 수정했습니다!

2024-06-10 08:44 UTC, xxziiko commented on week6/옹알이_2.ts
> +	}
[145291e](https://github.com/xxziiko/ts-snippets/pull/9/commits/145291e3d38084e514e025b3763cab9263b4c81c) 수정했습니다..!

2024-06-10 08:45 UTC, xxziiko commented
@f-lab-jake 멘토님 말씀 주신 내용 반영하여 수정했습니다!

2024-06-11 12:08 UTC, f-lab-jake requested changes

2024-06-11 12:08 UTC, f-lab-jake commented on week6/옹알이_2.ts
> +					found = true;
그냥 여기서 returng하면 안되나요?

2024-06-11 12:08 UTC, f-lab-jake commented on week6/홀짝에따라다른값반환하기.ts
> +	else for (let i = 2; i <= n; i += 2) result += i * i;
괜히 읽기힘들게 만들지 맙시다.

2024-06-12 01:26 UTC, xxziiko commented on week6/홀짝에따라다른값반환하기.ts
> +	else for (let i = 2; i <= n; i += 2) result += i * i;
@f-lab-jake 다시 작성했습니다!!

2024-06-13 11:49 UTC, f-lab-jake approved these changes

2024-06-13 11:50 UTC, f-lab-jake approved these changes

2024-06-13 11:50 UTC, f-lab-jake commented on week6/옹알이_2.ts
>  		let prevWord = "";
이런건 그냥 `let prevWord`가 낫습니다. 빈 배열로하는거에 딱히 근거가 없습니다.

2024-06-15 15:13 UTC, merged